GET http://localhost:3000/products

###
POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Maklorr",
    "image": "/img/maklor.webp",
    "price": 5000,
    "pieces": 10,
    "exp_date": ""
}

###
PATCH http://localhost:3000/products/663b3f3fab6acf0390fcef07
Content-Type: application/json

{
    "name": "Cireng isi Ayam Suwir",
    "price": 3000,
    "pieces": 10,
    "exp_date": ""
}

### 
DELETE http://localhost:3000/products/663b3f74ab6acf0390fcef0b

###
GET http://localhost:3000/buyers

###
GET http://localhost:3000/buyers/663c788874f06ca8aa1a36b6

###
POST http://localhost:3000/buyers
Content-Type: application/json

{
    "name": "Berto",
    "itemName": "Cireng",
    "totalItems": 5,
    "totalPricePaid": 13000,
    "totalChange": 0,
    "purchaseDate": "2024-05-09"
}

###
PATCH http://localhost:3000/buyers/663c788874f06ca8aa1a36b6
Content-Type: application/json

{
    "name": "Berton Petro",
    "itemName": "Cireng",
    "totalItems": 5,
    "totalPricePaid": 13000,
    "totalChange": 0,
    "purchaseDate": "2024-05-09"
}

###
DELETE http://localhost:3000/buyers/663cfedc6dddea956662a9f6